moved all relevant files into a src folder and added a docker file
UniversitaDellaCalabria/uniAuth pull request #35
Opened 2021-04-07 16:03 UTC by wibed

2021-04-07 16:37 UTC, wibed commented
AttributeError: 'HttpResponseRedirect' object has no attribute '_headers'

seems to be the cause on all tests.
could it be that the tests have not been updated?

2021-04-07 17:36 UTC, peppelinux commented
Ho @wibed, to claims:

1. Please push to Dev branch, can you rebase this PR?
2. Unittest failed

And more, I'm looking to decouple uniauth-saml2 Django app from uniAuth project. In the future I'd configure in tu a latter a future release of django-oidc-op. Does It sounds good to you?

uniAuth-saml2-idp would be installed as a puoi package

2021-04-07 22:27 UTC, peppelinux commented
yes tests are broken, I'm moving to gh actions and I'll update the entire project

idp and uniauth app will be merged in a single app. I'll take some days before come back on this PR that probably shall be refactored

2021-04-07 23:43 UTC, peppelinux commented
I've just fixed tests and moved relevant project files in the example folder.
more work has to be done from now.

ldap tests have been disabled in gh actions due to a very slow behaviour, with these coverage is up to 81%.
Feel free to adapt your PR on this latter update.

2021-04-07 23:43 UTC, peppelinux requested changes

2021-04-07 23:43 UTC, peppelinux commented on Dockerfile
> +RUN pip install \
why don't you use `pip install -r requirements.txt` here?

2021-04-08 10:08 UTC, peppelinux commented
Here:
https://github.com/UniversitaDellaCalabria/uniAuth/commit/7350cfaaf23b5a65cdda9ab9d1edac2447babcf1

any further updates here:
https://github.com/UniversitaDellaCalabria/uniAuth/issues/18

2021-04-08 18:21 UTC, wibed commented on Dockerfile
> +RUN pip install \
it wasn't clear that requirements.txt and requirements-dev.txt are dependent on each other.
as the first should be the minimal one and the second an extensive one.

2021-04-08 18:48 UTC, peppelinux commented on Dockerfile
> +RUN pip install \
requirements.txt is the minimal

-dev is for developers only
-docs for built sphinx
-customization for use additional backends, such ldap and other things.

For a good asset use the first and -customizations

2021-04-09 04:48 UTC, wibed commented on Dockerfile
> +RUN pip install \
I use requirements-dev.txt at #54
sadly until I got it to work I had to install a multitude of dependencies. 

I installed them globally as it is better documented
and could moved to a local installation later

2021-04-09 04:50 UTC, wibed commented
> Ho @wibed, two claims:
> 
> 1. Please push to Dev branch, can you rebase this PR?
> 2. Unittest failed
> 
> And more, I'm looking to decouple uniauth-saml2 Django app from uniAuth project. In the future I'd configure in this project a release of django-oidc-op. Does It sounds good to you?
> 
> uniAuth-saml2-idp would be installed as a pypi package

why don't you tag your releases and add push new features directly to master
don't get me wrong, I try to understand your decision

2021-04-09 04:50 UTC, wibed commented
> Ho @wibed, two claims:
> 
> 1. Please push to Dev branch, can you rebase this PR?
> 2. Unittest failed
> 
> And more, I'm looking to decouple uniauth-saml2 Django app from uniAuth project. In the future I'd configure in this project a release of django-oidc-op. Does It sounds good to you?
> 
> uniAuth-saml2-idp would be installed as a pypi package

why don't you tag your releases and add push new features directly to master
don't get me wrong, I try to understand your decision

2021-04-09 06:53 UTC, peppelinux commented
Actually master and Dev branch are sync.
Requirements files have been improved

2021-04-11 23:16 UTC, peppelinux commented
please rebase and test if you can, I made a lot of breaking changes

2021-04-12 18:44 UTC, wibed commented
please continue on #36

2021-04-12 20:14 UTC, closed without merging